# Generated by Django 2.2.10 on 2020-03-31 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0002_auto_20200320_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('control', 'Controller'), ('network', 'Network'), ('compute', 'Compute'), ('monitoring', 'Monitoring'), ('storage', 'storage')], max_length=50)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installers.Server')),
            ],
        ),
    ]
