# Generated by Django 2.2.10 on 2020-04-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0003_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_type', models.CharField(choices=[('source', 'Source')], default='source', max_length=50)),
                ('openstack_release', models.CharField(choices=[('train', 'Train')], default='train', max_length=50)),
                ('internal_vip_address', models.CharField(max_length=30)),
                ('external_vip_address', models.CharField(max_length=30)),
                ('enable_tls_on_external_api', models.BooleanField(default=True)),
                ('enable_ceph_service', models.BooleanField(default=True)),
                ('enable_cinder_service', models.BooleanField(default=True)),
                ('enable_magnum_service', models.BooleanField(default=True)),
                ('enable_vpnaas', models.BooleanField(default=True)),
                ('enable_fwaas', models.BooleanField(default=True)),
                ('enable_qos', models.BooleanField(default=True)),
                ('enable_ha_agent', models.BooleanField(default=True)),
                ('enable_provider_networks', models.BooleanField(default=True)),
                ('enable_port_forwading', models.BooleanField(default=True)),
                ('enable_octavia_service', models.BooleanField(default=True)),
                ('enable_promotheus_service', models.BooleanField(default=True)),
                ('ceph_pool_pg_num', models.CharField(default=30, max_length=30)),
                ('ceph_pool_pgp_num', models.CharField(default=30, max_length=30)),
                ('glance_backend_using_ceph', models.BooleanField(default=True)),
                ('glance_backend_file', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'inventory', 'verbose_name_plural': 'inventories'},
        ),
    ]
