# Generated by Django 2.2.10 on 2020-05-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0005_advancedconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='ceph_pool_pg_num',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='ceph_pool_pgp_num',
            field=models.IntegerField(default=30),
        ),
    ]
