# Generated by Django 2.2.10 on 2020-06-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0006_auto_20200519_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], max_length=255)),
            ],
        ),
    ]
