# Generated by Django 2.2.10 on 2020-11-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0009_auto_20200924_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='network_interface',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='neutron_plugin_agent',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='storage_interface',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
