# Generated by Django 2.2.10 on 2020-11-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0011_auto_20201125_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='ceph_pool_pg_num',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='ceph_pool_pgp_num',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
