# Generated by Django 2.2.10 on 2020-12-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0012_auto_20201125_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMAAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maas_api_key', models.CharField(max_length=100)),
                ('maas_url', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ConfigMAAS',
                'verbose_name_plural': 'ConfigMAASs',
            },
        ),
    ]
