# Generated by Django 2.2.10 on 2021-02-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0013_configmaas'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='neutron_external_interface',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
